# serverless.yml

service: happy-serverless

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'local'} # can also use ${env:stage, 'local'}
  region: us-east-2
  memorySize: ${file(./config/${self:provider.stage}.yml):provider.memory}
  timeout: 6
  environment:
    stage: ${self:provider.stage}
    database: ${file(./config/${self:provider.stage}.yml):database}

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: npm

package:
  individually: true

functions:
  app:
    handler: src/app.handler
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

  